apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: student-reg-webapp-ingress
  namespace: test-ns
spec:
   ingressClassName: nginx
   rules:
   - host: "studentregwebapp.atulittechnologies.in"
     http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: student-reg-webapp-svc
            port:
              number: 80 

